export default {
	damage: 'Damage',
	crit: 'Critical Chance',
	aps: 'Attacks per Second',
	dps: 'Damage per Second',
	edps: 'Elemental DPS',
	pdps: 'Physical DPS',
	ar: 'Armour',
	ev: 'Evasion',
	es: 'Energy Shield',
	block: 'Block',
	str: 'Strength',
	dex: 'Dexterity',
	int: 'Intelligence',
	lvl: 'Level',
	map_tier: 'Map Tier',
	map_packsize: 'Map Packsize',
	map_iir: 'Map IIR',
	map_iiq: 'Map IIQ',
	map_shaped: 'Shaped Map',
	map_elder: 'Elder Map',
	map_series: {
		title: 'Map Series',
		options: ['Legion', 'Synthesis', 'Betrayal', 'War for Atlas', 'Atlas of World', 'The Awakening', 'Legacy']
	},
	quality: 'Quality',
	ilvl: 'Item Level',
	gem_level_progress: 'Gem Experience %',
	gem_level: 'Gem Level',
	shaper_item: 'Shaper Item',
	elder_item: 'Elder Item',
	fractured_item: 'Fractured Item',
	synthesised_item: 'Synthesised Item',
	// identified: { option: null },
	alternate_art: 'Alternate Art',
	corrupted: 'Corrupted',
	mirrored: 'Mirroed',
	crafted: 'Crafted',
	veiled: 'Veiled',
	enchanted: 'Enchanted',
	talisman_tier: 'Talisman Tier',
	sockets: 'Sockets',
	links: 'Links'
};
