export const WEAPON_FILTERS = {
	DAMAGE: {
		SET_MIN: 'SET_MIN_DAMAGE',
		SET_MAX: 'SET_MAX_DAMAGE'
	},
	CRIT: {
		SET_MIN: 'SET_MIN_CRIT',
		SET_MAX: 'SET_MAX_CRIT'
	},
	APS: {
		SET_MIN: 'SET_MIN_APS',
		SET_MAX: 'SET_MAX_APS'
	},
	DPS: {
		SET_MIN: 'SET_MIN_DPS',
		SET_MAX: 'SET_MAX_DPS'
	},
	EDPS: {
		SET_MIN: 'SET_MIN_EDPS',
		SET_MAX: 'SET_MAX_EDPS'
	},
	PDPS: {
		SET_MIN: 'SET_MIN_PDPS',
		SET_MAX: 'SET_MAX_PDPS'
	}
};
export const ARMOUR_FILTERS = {
	AR: {
		SET_MIN: 'SET_MIN_AR',
		SET_MAX: 'SET_MAX_AR'
	},
	EV: {
		SET_MIN: 'SET_MIN_EV',
		SET_MAX: 'SET_MAX_EV'
	},
	ES: {
		SET_MIN: 'SET_MIN_ES',
		SET_MAX: 'SET_MAX_ES'
	},
	BLOCK: {
		SET_MIN: 'SET_MIN_BLOCK',
		SET_MAX: 'SET_MAX_BLOCK'
	}
};
export const REQUIREMENTS_FILTERS = {
	STR: {
		SET_MIN: 'SET_MIN_STR',
		SET_MAX: 'SET_MAX_STR'
	},
	DEX: {
		SET_MIN: 'SET_MIN_DEX',
		SET_MAX: 'SET_MAX_DEX'
	},
	INT: {
		SET_MIN: 'SET_MIN_INT',
		SET_MAX: 'SET_MAX_INT'
	},
	LVL: {
		SET_MIN: 'SET_MIN_LVL',
		SET_MAX: 'SET_MAX_LVL'
	}
};
export const MAP_FILTERS = {
	MAP_TIER: {
		SET_MIN: 'SET_MIN_MAP_TIER',
		SET_MAX: 'SET_MAX_MAP_TIER'
	},
	MAP_IIQ: {
		SET_MIN: 'SET_MIN_MAP_IIQ',
		SET_MAX: 'SET_MAX_MAP_IIQ'
	},
	MAP_PACKSIZE: {
		SET_MIN: 'SET_MIN_MAP_PACKSIZE',
		SET_MAX: 'SET_MAX_MAP_PACKSIZE'
	},
	MAP_IIR: {
		SET_MIN: 'SET_MIN_MAP_IIR',
		SET_MAX: 'SET_MAX_MAP_IIR'
	},
	MAP_SHAPED: {
		OPTION: 'SET_MAP_SHAPED'
	},
	MAP_ELDER: {
		OPTION: 'SET_MAP_ELDER'
	},
	MAP_SERIES: {
		OPTION: 'SET_MAP_SERIES'
	}
};
export const MISC_FILTERS = {
	QUALITY: {
		SET_MIN: 'SET_MIN_QUALITY',
		SET_MAX: 'SET_MAX_QUALITY'
	},
	ILVL: {
		SET_MIN: 'SET_MIN_ILVL',
		SET_MAX: 'SET_MAX_ILVL'
	},
	GEM_LEVEL_PROGRESS: {
		SET_MAX: 'SET_MAX_GEM_LEVEL_PROGRESS',
		SET_MIN: 'SET_MIN_GEM_LEVEL_PROGRESS'
	},
	GEM_LEVEL: {
		SET_MIN: 'SET_MIN_GEM_LEVEL',
		SET_MAX: 'SET_MAX_GEM_LEVEL'
	},
	SHAPER_ITEM: {
		OPTION: 'SET_SHAPER_ITEM'
	},
	ELDER_ITEM: {
		OPTION: 'SET_ELDER_ITEM'
	},
	FRACTURED_ITEM: {
		OPTION: 'SET_FRACTURED_ITEM'
	},
	SYNTHESISED_ITEM: {
		OPTION: 'SET_SYNTHESISED_ITEM'
	},
	// identified: { OPTION: null },
	ALTERNATE_ART: {
		OPTION: 'SET_ALTERNATE_ART'
	},
	CORRUPTED: {
		OPTION: 'SET_CORRUPTED'
	},
	MIRRORED: {
		OPTION: 'SET_MIRRORED'
	},
	CRAFTED: {
		OPTION: 'SET_CRAFTED'
	},
	VEILED: {
		OPTION: 'SET_VEILED'
	},
	ENCHANTED: {
		OPTION: 'SET_ENCHANTED'
	},
	TALISMAN_TIER: {
		SET_MIN: 'SET_MIN_TALISMAN_TIER',
		SET_MAX: 'SET_MAX_TALISMAN_TIER'
	}
};
export const SOCKET_FILTERS = {
	SOCKETS: {
		R: 'SET_MIN_R_SOCKETS',
		G: 'SET_MIN_G_SOCKETS',
		B: 'SET_MIN_B_SOCKETS',
		W: 'SET_MIN_W_SOCKETS',
		SET_MIN: 'SET_MIN_SOCKETS',
		SET_MAX: 'SET_MAX_SOCKETS'
	},
	LINKS: {
		W: 'SET_MIN_W_LINKS',
		B: 'SET_MIN_B_LINKS',
		G: 'SET_MIN_G_LINKS',
		R: 'SET_MIN_R_LINKS',
		SET_MAX: 'SET_MIN_LINKS',
		SET_MIN: 'SET_MAX_LINKS'
	}
};
export const STAT_FILTERS = {
	TYPE: 'SET_FILTER_TYPE',
	FILTERS: [
		{
			ID: 'SET_FILTER_ID',
			VALUE: {
				MIN: 'SET_FILTER_MIN',
				MAX: 'SET_FILTER_MAX'
			}
		}
	]
};
export const SET_STAT_FILTER = 'SET_STAT_FILTER';
export const SET_STAT_FILTER_MIN = 'SET_STAT_FILTER_MIN';
export const SET_STAT_FILTER_MAX = 'SET_STAT_FILTER_MAX';
export const SET_STAT_FILTER_TYPE = 'SET_STAT_FILTER_TYPE';
export const ADD_STAT_FILTER_TO_GROUP = 'ADD_STAT_FILTER_TO_GROUP';
export const ADD_STAT_FILTER_GROUP = 'ADD_STAT_FILTER_GROUP';
export const REMOVE_STAT_FILTER_GROUP = 'REMOVE_STAT_FILTER_GROUP';
export const REMOVE_STAT_FILTER_FROM_GROUP = 'REMOVE_STAT_FILTER_FROM_GROUP';

export const APP_STATE = {
	SET_SEARCH_STATE: 'SET_SEARCH_STATE',
	ADD_SEARCH_RESULTS: 'ADD_SEARCH_RESULTS',
	SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
	SET_SEARCH_TERM: 'SET_SEARCH_TERM',
	SET_SEARCH_FORM_VISIBLE: 'SET_SEARCH_FORM_VISIBLE',
	SET_SEARCH_RESULTS_PAGE: 'SET_RESULTS_PAGE',
	SET_SEARCH_RESULTS_IDS: 'SET_SEARCH_RESULTS_IDS',
	CLEAR_FILTERS: 'CLEAR_FILTERS'
};

export const BULK = {
	SET_HAVE: 'SET_HAVE',
	SET_WANT: 'SET_WANT',
	SET_RESULTS: 'SET_BULK_RESULTS',
	ADD_RESULTS: 'ADD_BULK_RESULTS',
	SET_REVERSE_RESULTS: 'SET_REVERSE_RESULTS',
	ADD_NEW_SEARCH: 'ADD_NEW_BULK_SEARCH',
	TOGGLE_SEARCH_FORM_VISIBILITY: 'TOGGLE_SEARCH_FORM_VISIBILITY',
	SET_PROGRESS: 'SET_BULK_PROGRESS'
};
